In [1]:
import numpy as np

Ques.No.1

In [24]:
x = np.array([1,2,3,4,5])
N = 5
matrix = np.column_stack([x**(N-i-1) for i in range(N)])
matrix

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

In [25]:
y = np.array([1,2,3,4,5])
N = 5
matrix1 = np.vander(y , increasing=False)
matrix1

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

Ques.No.2

In [26]:
data = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
data

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [28]:
def moving_avg(values,window):
    return np.convolve(values,np.ones(window),'valid')/window

moving_avg(data,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])